export enum Action_Type {
  ADD_NEW_RECIPE = "ADD_NEW_RECIPE",
  DELETE_RECIPE = "DELETE_RECIPE",
  UPDATE_RECIPE = "UPDATE_RECIPE",
  ADD_TO_SHOPPINGLIST = "ADD_TO_SHOPPINGLIST",
  ADD_NEW_INGREDIENT = "ADD_NEW_INGREDIENT",
  UPDATE_INGREDEINT = "UPDATE_INGREDIENT",
  UPDATE_MODE = "UPDATE_MODE",
  DELETE_INGEREDEINT = "DELETE_INGREDEINT",
  UPDATE_ACTIVE_ID = "UPDATE_ACTIVE_ID",
}